services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: projektzeiterfassung-db
    user: root
    environment:
      SA_PASSWORD: "Your@Strong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    volumes:
      - sql_data:/var/opt/mssql
      - ./docker/db/init.sql:/usr/src/init.sql:ro
    command: 
      - /bin/bash
      - -c
      - |
        # Install required packages
        apt-get update && apt-get install -y mssql-tools unixodbc-dev
        
        # Start SQL Server directly
        /opt/mssql/bin/sqlservr &
        
        # Wait for SQL Server to initialize
        sleep 30
        
        # Run the initialization script
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Your@Strong!Passw0rd" -d master -i /usr/src/init.sql
        
        # Keep container running
        while sleep 1000; do :; done
    ports:
      - "1433"
    restart: always
    healthcheck:
      test: "/opt/mssql-tools/bin/sqlcmd -U sa -P 'Your@Strong!Passw0rd' -Q 'SELECT 1' > /dev/null 2>&1 || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
    restart: always

volumes:
  sql_data:
